import { Image, Platform, StyleSheet, Text, View } from 'react-native'
import React, { useState } from 'react'
import ThemedView from '../components/ThemedView'
import ThemedText from '../components/ThemedText'
import ThemedTextInput from '../components/ThemedTextInput'
import ThemedButton from '../components/ThemedButton'
import { Toast } from 'toastify-react-native'
import axios from 'axios'

const ChildTrack = () => {
    const [code, onCodeChange] = useState()
    const [name, onNameChange] = useState()
    async function handleSubmit() {
        const childData = {
            name: name,
            code: code
        }
        const baseUrl = Platform.OS === "android" ? "http://192.168.137.1:5000/child_code" : "http://localhost:5000/child_code"
        axios.post(baseUrl, childData, {withCredentials: true}).
        then((res) => {
            if(res.data.status === "ok"){
                Toast.show({
                    type: "success",
                    text1: res.data.data,
                    useModal: false
                })

            }else{
                Toast.show({
                    type: "error",
                    text1: res.data.data,
                    useModal: false
                })
                console.error(res.data.data)
            }
        }).catch(err => {
            Toast.show({
                type: "error",
                text1: "Something went wrong when submiting details",
                useModal: false
            })
            console.error(err);
        })
    }

  return (
    <ThemedView style={styles.container}>
        <Image source={require("../assets/images/bg.jpg")} style={styles.bgImage}/>
      <ThemedText style={styles.heading}>Kid ConnecT Child Track</ThemedText>
      <ThemedText style={styles.paraText}> please enter the code generated by your guardian below</ThemedText>
      <ThemedTextInput value={code} onChangeText={onCodeChange} style={styles.textStyle} placeholder = "Track code"/>
      <ThemedTextInput value={name} onChangeText={onNameChange} style={styles.textStyle} placeholder = "Name"/>
      <ThemedButton onPress = {() => {
        handleSubmit()
      }}> 
        <ThemedText style={styles.btnText}>SUBMIT</ThemedText>
      </ThemedButton>
    </ThemedView>
  )
}

export default ChildTrack

const styles = StyleSheet.create({
    container:{
        justifyContent: "center",
        alignItems: "center",
        zIndex: 1000
    },
    bgImage:{
        ...StyleSheet.absoluteFillObject,
        width:"100%",
        height:"100%",
        opacity: 0.7
    },
    textStyle:{
        zIndex: 1,
    },
    heading: {  
        zIndex: 1,
        fontSize: 30,
        fontWeight: "bold",
        color: "black",
    },
    paraText:{
        fontStyle: "italic",
        fontWeight: "700",
        zIndex: 1,
        color: "black",
    },
    btnText: {
        color: "black",
    }
})